Feature/9 refactor get public did call (renamed from reference architecture
didx-xyz/aries-cloudapi-python pull request #19
Opened 2021-06-11 08:22 UTC by michaelwiles

Included here in is rename and group the facades - introduced acapy_ledger_facade and acapy_wallet_facade

We need to do some maturation of the mechanism for locating the aries agent controller.

2021-06-11 08:26 UTC, michaelwiles commented on .github/workflows/continuous-build.yml
> +        pip install pytest pytest-custom_exit_code
this is relevant as other wise pytest exits with 1 when tests fail so the build does not continue - we want the build to continue as we want sonar to run even when tests fail.

2021-06-11 08:27 UTC, michaelwiles commented on app/acapy_wallet_facade.py
> +import logging
see comment for acapy_ledger_facade

2021-06-11 08:27 UTC, michaelwiles commented on app/core/wallet.py
> +from typing import Optional
introduced a core wallet call

2021-06-11 08:28 UTC, michaelwiles commented on app/core/wallet.py
> +from typing import Optional
@morrieinmaas thanks for your changes - look how much more lightweight this call is!

2021-06-11 08:29 UTC, michaelwiles commented on app/facade.py
> +async def create_controller(place_holder) -> AriesAgentControllerBase:
need to do some work in this context - defoes need to introduce that fast api dependency

2021-06-11 08:29 UTC, michaelwiles commented on app/facade.py
> -async def create_did(controller):
moved to relevant ledger or wallet facade

2021-06-11 08:30 UTC, michaelwiles commented on app/facade.py
> -async def get_taa(controller):
moved to acapy_ledger_facade

2021-06-11 08:31 UTC, michaelwiles commented on app/tests/test_wallet.py
> +
even this simple test was very helpful to validate the call was working (after the refactor)

2021-06-11 08:33 UTC, michaelwiles commented on app/acapy_wallet_facade.py
> +async def assign_public_did(controller: AriesAgentControllerBase, did: str):
changed this method to take a did as a string (not a did object). 

The only thing used by the call is the did so did object is unnecessary abstraction.

2021-06-14 08:36 UTC, morrieinmaas commented
Overall looking really good. I need to go through this in detail again though. 

One thing that definitely needs addressing is the SonarCloud quality gate. If we introduce changes and coverage needs to be 80% for new code then this should also pass/hold true for this PR.

2021-06-15 09:01 UTC, morrieinmaas requested changes

2021-06-15 15:48 UTC, merged